Repository kiransbaliga/Network-Lab, pull requests merged in 2022-10, with the labels that each got.

#1 Minor changes and security patches
  Concurrent File Server UDP/client.c
  Concurrent File Server UDP/server.c
  Concurrent File System/client.c
  Concurrent File System/server.c
Labels: good first issue, hacktoberfest-accepted

#2 comments in tcp code for better understanding
  Multi user chat/client1.c
  Multi user chat/server1.c
Labels: good first issue, hacktoberfest-accepted

#3 added new code absolute loader and fixed bugs improved code efficiency
  .vscode/settings.json
  Concurrent File Server UDP/as.c
  Concurrent File Server UDP/server.c
  Distance-Vector/Program method-2.c
  Distance-Vector/exp2.c
  Go-Back-N/onepass.c
  leakybucket/abloader.c
Labels: good first issue, hacktoberfest-accepted

#4 User interface changed
  Go-Back-N/onepass.c
Labels: good first issue, hacktoberfest-accepted

#5 Update client.c
  Concurrent File System/client.c
Labels: good first issue, hacktoberfest-accepted

#6 Update client.c
  Go-Back-N/client.c
Labels: good first issue, hacktoberfest-accepted

#7 Added Meaningful comments
  leakybucket/leakybucket.c
Labels: enhancement, hacktoberfest-accepted

#8 created readme
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#9 Some Descriptions Added
  Distance-Vector/Program method-2.c
Labels: documentation, good first issue, hacktoberfest-accepted

#10 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#11 Update Program.c
  Distance-Vector/Program.c
Labels: enhancement, hacktoberfest-accepted
